export const PAGE_INCREMENT = 'PAGE_INCREMENT'

export const PAGE_DECREMENT = 'PAGE_DECREMENT'

export const IS_PAGE_CLICK_TRUE = 'IS_PAGE_CLICK_TRUE'

export const IS_PAGE_CLICK_FALSE = 'IS_PAGE_CLICK_FALSE'

export const TYPE_CHANGE = 'TYPE_CHANGE'

export const IS_TYPE_CLICK_TRUE = 'IS_TYPE_CLICK_TRUE'

export const IS_TYPE_CLICK_FALSE = 'IS_TYPE_CLICK_FALSE'

export const INPUT_CHANGE = 'INPUT_CHANGE'

export const IS_INPUT_CLICK_TRUE = 'IS_INPUT_CLICK_TRUE'

export const IS_INPUT_CLICK_FALSE = 'IS_INPUT_CLICK_FALSE'